### ISSUE TITLE
Sign Up & Log In JS

### ISSUE THREAD

**Issue by BradsherC** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#13]
I wrote some JS in the <head>s of these pages, but it does not currently work.

**Comment by SuperUltraMegaChicken** [comment]
There are two main issues with the code. 

The first is that the original parameter passed, didn't do anything. Instead, I replaced it with `event` which in this context is the submit event. An important detail about the the submit event is that once the function returns a non false value, it will try to perform whatever the action is. That action is dependent on the form attribute `action`. If the `action` is empty, then it will still perform "nothing". The point is that any state in your page gets lost because on the submit event, it essentially refreshes the page. You circumvent this by calling the event's `preventDefault()` method. As the name implies, it prevents the submit event's default action... which is to redirect to wherever action is. Now password errors can be loaded because clicking the button no longer refreshes the page.

The second issue is the whole redirection part. Your `$("#login").attr("action", "/admin_homepage.html")` doesn't work because you treat the ordering as such, user clicks submit, the action gets stored, the function runs, you change the action but the action you changed it to doesn't get stored, the function ends, and it calls the stored action (assuming we're not using `event.preventDefault()`. This action was previously nothing, which will just refresh the page. To play around this, we call a global function in the window object called `location`. You can also call `window.location` but `window` by default, is predefined. `location` has a method called `replace` and we can use that to change the url to something else, like the admin homepage.
