### ISSUE TITLE
deleteItem JS

### ISSUE THREAD

**Issue by BradsherC** [RPI-ITWS/ITWS-2110-F24-LuckyCharms#55]
I wrote a query (in backend/bradsc-delete-item), in deleteItem.php, which I think works, but my changes to admin.js and lablist_and_checkout.js don't work. When the fetch request is sent to the PHP with the itemID as a query parameter, it is passed in as "undefined". I don't know why this is happening, since the same thing seems to work fine for the checkout query.

**Comment by SuperUltraMegaChicken** [comment]
Fixed in your branch.

In your [code](https://github.com/RPI-ITWS/ITWS-2110-F24-LuckyCharms/blob/bradsc-delete-item/admin/admin.js#L139), you had this line replace the onclick function with a new onclick function. That new function does not pass any parameters, therefore in the function, it is deemed undefined.
